export const fruits = [
  {
    id: 1,
    title: "Peach",
    price: "4.99",
    description:
      "Cultivated in natural environments, organic peachs are delivered directly from nature to consumers.",
    category: "fruits",
    image:
      "https://cdn.pixabay.com/photo/2022/08/18/19/56/peaches-7395592_640.jpg",
    count: 120,
  },
  {
    id: 2,
    title: "Strawberry",
    price: "3.49",
    description:
      "Cultivated in natural environments, organic strawberries are delivered directly from nature to consumers.",
    category: "fruits",
    image:
      "https://cdn.pixabay.com/photo/2014/02/23/11/11/strawberries-272812_640.jpg",
    count: 120,
  },
  {
    id: 3,
    title: "Blackberry",
    price: "5.99",
    description:
      "Cultivated in natural environments, organic strawberries are delivered directly from nature to consumers.",
    category: "fruits",
    image: "https://cdn.pixabay.com/photo/2010/12/13/10/05/berry-2275_640.jpg",
    count: 120,
  },
  {
    id: 4,
    title: "Grape",
    price: "3.99",
    description:
      "Cultivated in natural environments, organics grape are delivered directly from nature to consumers.",
    category: "fruits",
    image:
      "https://cdn.pixabay.com/photo/2017/02/02/14/04/grapes-2032838_640.jpg",
    count: 120,
  },
  {
    id: 5,
    title: "Pear",
    price: "3.75",
    description:
      "Cultivated in natural environments, organic pears are delivered directly from nature to consumers.",
    category: "fruits",
    image:
      "https://cdn.pixabay.com/photo/2018/07/09/17/56/pear-tree-3526690_640.jpg",
    count: 120,
  },
  {
    id: 6,
    title: "Plum",
    price: "4.25",
    description:
      "Cultivated in natural environments, organic plums are delivered directly from nature to consumers.",
    category: "fruits",
    image:
      "https://media.istockphoto.com/id/179265573/fr/photo/prunes-fra%C3%AEches-isol%C3%A9-sur-blanc.jpg?s=612x612&w=0&k=20&c=9hOne2ikdP9omEXJhm1QaMsawcbcK0IdGCsdflAjW7o=",
    count: 120,
  },
  {
    id: 7,
    title: "Pomegranate",
    price: "3.99",
    description:
      "Cultivated in natural environments, organic pomegranates are delivered directly from nature to consumers.",
    category: "fruits",
    image:
      "https://media.istockphoto.com/id/1066838260/fr/photo/un-entier-et-une-partie-dune-grenade-avec-graines-de-grenade-et-feuilles-isol%C3%A9s-sur-fond.jpg?s=612x612&w=0&k=20&c=e3weWlLKglwiMNCSNS1102aDT6zJfJ4oUzFCLUELmcE=",
    count: 120,
  },
  {
    id: 8,
    title: "Orange",
    price: "2.99",
    description:
      "Cultivated in natural environments, organic oranges are delivered directly from nature to consumers.",
    category: "fruits",
    image:
      "https://media.istockphoto.com/id/522897227/fr/photo/orange.jpg?s=612x612&w=0&k=20&c=K3mL90nU-5pmphcpT-LkoSGDPpY_-d19-UGmImK4R4k=",
    count: 120,
  },
  {
    id: 9,
    title: "Melon",
    price: "2",
    description:
      "Cultivated in natural environments, organic melons are delivered directly from nature to consumers.",
    category: "fruits",
    image:
      "https://cdn.pixabay.com/photo/2016/03/05/22/31/food-1239302_640.jpg",
    count: 120,
  },
  {
    id: 10,
    title: "Quince",
    price: "2.99",
    description: "Cultivated in natural environments, organic quinces are delivered directly from nature to consumers.",
    category: "fruits",
    image:
      "https://cdn.pixabay.com/photo/2012/11/07/17/34/quince-65189_640.jpg",
    count: 120,
  },
  {
    id: 11,
    title: "Figue",
    price: "6.99",
    description: "Cultivated in natural environments, organic figues are delivered directly from nature to consumers.",
    category: "fruits",
    image: "https://media.istockphoto.com/id/1255893408/fr/photo/figues-isol%C3%A9es-sur-le-fond-blanc-avec-le-chemin-de-d%C3%A9coupage.jpg?s=612x612&w=0&k=20&c=zEGu5nMIuvIuFzVSiR99R9D7mSm6LcOiJlcRz6APz1A=",
    count: 120,
  },
  {
    id: 12,
    title: "Banana",
    price: "2.99",
    description: "Cultivated in natural environments, organic bananas are delivered directly from nature to consumers.",
    category: "fruits",
    image: "https://cdn.pixabay.com/photo/2017/06/27/22/21/banana-2449019_640.jpg",
    count: 120,
  },
  {
    id: 13,
    title: "Apricot",
    price: "3.45",
    description: "Cultivated in natural environments, organic apricots are delivered directly from nature to consumers.",
    category: "fruits",
    image: "https://cdn.pixabay.com/photo/2019/05/17/21/22/apricots-4210720_640.jpg",
    count: 120,
  },
  {
    id: 14,
    title: "Cherry",
    price: "4.99",
    description: "Cultivated in natural environments, organic cherries are delivered directly from nature to consumers.",
    category: "fruits",
    image: "https://cdn.pixabay.com/photo/2013/07/26/03/42/cherry-167341_640.jpg",
    count: 120,
  },
  {
    id: 15,
    title: "Apple",
    price: "3.99",
    description: "Cultivated in natural environments, organic apples are delivered directly from nature to consumers.",
    category: "fruits",
    image: "https://cdn.pixabay.com/photo/2016/11/18/13/47/apple-1834639_640.jpg",
    count: 120,
  },
  {
    id: 16,
    title: "Onion",
    price: "1.99",
    description: "Cultivated in natural environments, organic onions are delivered directly from nature to consumers.",
    category: "vegetables",
    image: "https://cdn.pixabay.com/photo/2013/02/21/19/14/onion-bulbs-84722_640.jpg",
    count: 120,
  },
  {
    id: 17,
    title: "Potatoes",
    price: "1.55",
    description: "Cultivated in natural environments, organic potatoes are delivered directly from nature to consumers.",
    category: "vegetables",
    image: "https://cdn.pixabay.com/photo/2012/12/24/08/39/agriculture-72254_640.jpg",
    count: 120,
  },
  {
    id: 18,
    title: "Carrot",
    price: "2.50",
    description: "Cultivated in natural environments, organic carrots are delivered directly from nature to consumers.",
    category: "vegetables",
    image: "https://cdn.pixabay.com/photo/2016/01/25/13/45/carrots-1160683_640.jpg",
    count: 120,
  },
  {
    id: 19,
    title: "Aubergine",
    price: "2.00",
    description: "Cultivated in natural environments, organic aubergine are delivered directly from nature to consumers.",
    category: "vegetables",
    image: "https://cdn.pixabay.com/photo/2018/11/17/15/29/eggplant-3821293_640.jpg",
    count: 120,
  },
  {
    id: 20,
    title: "Courgettes",
    price: "2.00",
    description: "Cultivated in natural environments, organic courgettes are delivered directly from nature to consumers.",
    category: "vegetables",
    image: "https://cdn.pixabay.com/photo/2020/07/09/15/24/courgettes-5387743_1280.jpg",
    count: 120,
  },
  {
    id: 21,
    title: "Pumpkin",
    price: "3.99",
    description: "Cultivated in natural environments, organic pumpkins are delivered directly from nature to consumers.",
    category: "vegetables",
    image: "https://cdn.pixabay.com/photo/2018/04/29/18/42/pumpkin-3360793_640.jpg",
    count: 120,
  },
  {
    id: 22,
    title: "Tomatoes",
    price: "2.99",
    description: "Cultivated in natural environments, organic tomatoes are delivered directly from nature to consumers.",
    category: "vegetables",
    image: "https://cdn.pixabay.com/photo/2016/08/01/17/08/tomatoes-1561565_640.jpg",
    count: 120,
  },
  {
    id: 23,
    title: "Cucumbers",
    price: "1.99",
    description: "Cultivated in natural environments, organic cucumbers are delivered directly from nature to consumers.",
    category: "vegetables",
    image: "https://cdn.pixabay.com/photo/2016/08/12/15/33/cucumbers-1588945_1280.jpg",
    count: 120,
  },
  {
    id: 24,
    title: "Spinach",
    price: "3.99",
    description: "Cultivated in natural environments, organic spinach are delivered directly from nature to consumers.",
    category: "vegetables",
    image: "https://cdn.pixabay.com/photo/2016/11/05/00/05/spinach-1799266_640.jpg",
    count: 120,
  },
  {
    id: 25,
    title: "Parsley",
    price: "1.00",
    description: "Cultivated in natural environments, organic parsley are delivered directly from nature to consumers.",
    category: "vegetables",
    image: "https://cdn.pixabay.com/photo/2016/03/29/01/06/cilantro-1287301_640.jpg",
    count: 120,
  },
  {
    id: 26,
    title: "Mint",
    price: "1.00",
    description: "Cultivated in natural environments, organic mint are delivered directly from nature to consumers.",
    category: "vegetables",
    image: "https://cdn.pixabay.com/photo/2016/06/03/17/09/mint-1433826_640.jpg",
    count: 120,
  },
  {
    id: 27,
    title: "Red cabbage",
    price: "1.99",
    description: "Cultivated in natural environments, organic red cabbage are delivered directly from nature to consumers.",
    category: "vegetables",
    image: "https://cdn.pixabay.com/photo/2018/06/28/00/17/red-3502931_640.jpg",
    count: 120,
  },
  {
    id: 28,
    title: "Cabbage",
    price: "1.99",
    description: "Cultivated in natural environments, organic cabbage are delivered directly from nature to consumers.",
    category: "vegetables",
    image: "https://cdn.pixabay.com/photo/2015/09/25/16/51/cabbage-957778_640.jpg",
    count: 120,
  }, 
];

export const categories = ["all", "fruits", "vegetables"];
